// packages/svelte/src/lib/components/FeedbackButton.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type {
    FeedbackAttachment,
    FeedbackInput,
    SubmitResult,
  } from '@tatlacas/brevwick-sdk';
  import { getFeedback, type FeedbackStatus } from '../context';
  import { BREVWICK_SVELTE_VERSION } from '../internal/version';

  /** Corner the FAB pins to. Default `'bottom-right'`. */
  export let position: 'bottom-right' | 'bottom-left' = 'bottom-right';
  /** When true, the FAB renders as disabled and cannot open the dialog. */
  export let disabled: boolean = false;
  /** When true, the component renders nothing. Useful for feature-flagging. */
  export let hidden: boolean = false;
  /** FAB label. Default `'Feedback'`. */
  export let label: string = 'Feedback';
  /** Force a palette regardless of the OS `prefers-color-scheme` setting. */
  export let theme: 'light' | 'dark' | 'system' = 'system';
  /** Fired with the SDK's `SubmitResult` after every submit (success or failure). */
  export let onSubmit: ((result: SubmitResult) => void) | undefined = undefined;

  // Combined screenshot + file cap, mirrored from the SDK's
  // MAX_ATTACHMENT_COUNT in packages/sdk/src/submit.ts. Enforced in the UI
  // so the user can't queue an attachment the SDK would reject downstream.
  const MAX_ATTACHMENTS = 5;

  // Resolved during component init so getContext() finds the parent layout's
  // setBrevwickContext call — Svelte requires getContext to run on the
  // initialisation call stack, not from inside onMount.
  const feedback = getFeedback();
  const status = feedback.status;

  let mounted = false;
  let open = false;
  let draft = '';
  let screenshots: { id: number; blob: Blob; url: string }[] = [];
  let files: { id: number; file: File }[] = [];
  let capturing = false;
  let submitError: string | null = null;
  let successAt: number | null = null;
  let screenshotId = 0;
  let fileId = 0;

  $: attachmentCount = screenshots.length + files.length;
  $: attachmentsAtCap = attachmentCount >= MAX_ATTACHMENTS;
  $: canSend = draft.trim().length > 0 && $status !== 'submitting' && !capturing;

  onMount(() => {
    mounted = true;
    return () => {
      // Revoke any object URLs left behind on unmount so a HMR cycle doesn't
      // leak previews between renders.
      for (const s of screenshots) URL.revokeObjectURL(s.url);
    };
  });

  function toggleOpen(): void {
    if (disabled) return;
    open = !open;
    if (open) {
      successAt = null;
      submitError = null;
    }
  }

  function closePanel(): void {
    open = false;
  }

  async function handleScreenshot(): Promise<void> {
    if (capturing || attachmentsAtCap) return;
    submitError = null;
    capturing = true;
    try {
      const blob = await feedback.captureScreenshot();
      // Defence-in-depth: a long-running capture started before files were
      // attached can still land after the combined total reached the cap.
      if (screenshots.length + files.length >= MAX_ATTACHMENTS) {
        submitError = `Maximum ${MAX_ATTACHMENTS} attachments reached`;
        return;
      }
      screenshots = [
        ...screenshots,
        {
          id: ++screenshotId,
          blob,
          url: URL.createObjectURL(blob),
        },
      ];
    } catch (err) {
      submitError = err instanceof Error ? err.message : 'Screenshot failed';
    } finally {
      capturing = false;
    }
  }

  function handleFiles(event: Event): void {
    const input = event.target as HTMLInputElement;
    const list = input.files;
    if (!list || list.length === 0) return;
    const remaining = MAX_ATTACHMENTS - (files.length + screenshots.length);
    if (remaining <= 0) {
      input.value = '';
      return;
    }
    const next: { id: number; file: File }[] = [];
    for (let i = 0; i < Math.min(remaining, list.length); i++) {
      next.push({ id: ++fileId, file: list.item(i)! });
    }
    files = [...files, ...next];
    input.value = '';
  }

  function removeScreenshot(id: number): void {
    const target = screenshots.find((s) => s.id === id);
    if (target) URL.revokeObjectURL(target.url);
    screenshots = screenshots.filter((s) => s.id !== id);
  }

  function removeFile(id: number): void {
    files = files.filter((f) => f.id !== id);
  }

  async function handleSubmit(): Promise<void> {
    if (!canSend) return;
    if (!draft.trim()) {
      submitError = 'Please describe what happened.';
      return;
    }
    submitError = null;

    const attachments: Array<Blob | FeedbackAttachment> = [];
    screenshots.forEach((s, idx) => {
      const ext = s.blob.type.split('/')[1]?.split('+')[0] || 'webp';
      const filename =
        screenshots.length === 1
          ? `screenshot.${ext}`
          : `screenshot-${idx + 1}.${ext}`;
      attachments.push({ blob: s.blob, filename });
    });
    for (const { file } of files)
      attachments.push({ blob: file, filename: file.name });

    const derivedTitle = draft.trim().split('\n', 1)[0]!.slice(0, 120);
    const input: FeedbackInput = {
      title: derivedTitle,
      description: draft,
      attachments: attachments.length ? attachments : undefined,
    };

    const submittedScreenshots = screenshots;
    try {
      const result = await feedback.submit(input);
      onSubmit?.(result);
      if (result.ok) {
        successAt = Date.now();
        draft = '';
        for (const s of submittedScreenshots) URL.revokeObjectURL(s.url);
        screenshots = [];
        files = [];
      } else {
        submitError = result.error.message;
      }
    } catch (err) {
      submitError =
        err instanceof Error && err.message
          ? err.message
          : 'We could not submit your feedback. Please try again.';
    }
  }

  function handleKeydown(event: KeyboardEvent): void {
    if (
      event.key === 'Enter' &&
      !event.shiftKey &&
      !event.ctrlKey &&
      !event.metaKey &&
      !event.altKey &&
      !event.isComposing
    ) {
      event.preventDefault();
      void handleSubmit();
    }
  }

  function formatSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} kB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  // Inferred so `pos` re-derives when `position` is reactive-changed.
  $: fabPosClass = position === 'bottom-left' ? 'brw-fab-bl' : 'brw-fab-br';
  $: panelPosClass =
    position === 'bottom-left' ? 'brw-panel-bl' : 'brw-panel-br';
</script>

{#if !hidden && mounted}
  <div class="brw-svelte-root" data-brw-theme={theme} data-brevwick-skip>
    {#if open}
      <div
        class="brw-svelte-panel {panelPosClass}"
        role="dialog"
        aria-modal="false"
        aria-label="Send feedback"
        data-brevwick-skip
      >
        <header class="brw-svelte-header">
          <span class="brw-svelte-avatar" aria-hidden="true">B</span>
          <span class="brw-svelte-title">Send feedback</span>
          <button
            type="button"
            class="brw-svelte-icon-btn"
            aria-label="Close"
            on:click={closePanel}
          >
            ×
          </button>
        </header>

        <div class="brw-svelte-thread" role="log" aria-live="polite">
          <div class="brw-svelte-bubble brw-svelte-bubble--assistant">
            Hi! Tell us what's happening. A screenshot helps if you have one.
          </div>

          {#each screenshots as shot, idx (shot.id)}
            <div class="brw-svelte-chip">
              <img
                src={shot.url}
                alt=""
                class="brw-svelte-chip-thumb"
              />
              <span class="brw-svelte-chip-name"
                >{screenshots.length === 1
                  ? 'screenshot'
                  : `screenshot ${idx + 1}`}</span
              >
              <span class="brw-svelte-chip-size">{formatSize(shot.blob.size)}</span>
              <button
                type="button"
                class="brw-svelte-chip-remove"
                aria-label={`Remove screenshot ${idx + 1}`}
                on:click={() => removeScreenshot(shot.id)}
              >
                ×
              </button>
            </div>
          {/each}

          {#each files as f (f.id)}
            <div class="brw-svelte-chip">
              <span class="brw-svelte-chip-name">{f.file.name}</span>
              <span class="brw-svelte-chip-size">{formatSize(f.file.size)}</span>
              <button
                type="button"
                class="brw-svelte-chip-remove"
                aria-label={`Remove ${f.file.name}`}
                on:click={() => removeFile(f.id)}
              >
                ×
              </button>
            </div>
          {/each}

          {#if capturing}
            <div class="brw-svelte-bubble brw-svelte-bubble--assistant">
              Capturing screenshot…
            </div>
          {/if}

          {#if submitError}
            <div class="brw-svelte-error" role="alert">{submitError}</div>
          {/if}

          {#if $status === 'submitting'}
            <div class="brw-svelte-bubble brw-svelte-bubble--assistant">
              Sending…
            </div>
          {/if}

          {#if successAt !== null}
            <div
              class="brw-svelte-bubble brw-svelte-bubble--assistant brw-svelte-bubble--receipt"
              role="status"
            >
              Thanks — your issue is on its way.
            </div>
          {/if}
        </div>

        <div class="brw-svelte-composer">
          <button
            type="button"
            class="brw-svelte-icon-btn"
            aria-label={attachmentsAtCap
              ? `Maximum ${MAX_ATTACHMENTS} attachments reached`
              : capturing
                ? 'Capturing screenshot…'
                : 'Capture screenshot of this page'}
            on:click={handleScreenshot}
            disabled={capturing ||
              attachmentsAtCap ||
              $status === 'submitting'}
          >
            <svg
              viewBox="0 0 24 24"
              width="18"
              height="18"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <rect x="3" y="5" width="18" height="12" rx="2" />
              <rect
                x="7"
                y="8"
                width="10"
                height="6"
                rx="1"
                stroke-dasharray="2 2"
              />
            </svg>
          </button>
          <label class="brw-svelte-icon-btn" aria-label="Attach file">
            <svg
              viewBox="0 0 24 24"
              width="18"
              height="18"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path
                d="M21 10.5l-8.5 8.5a5 5 0 0 1-7-7l9-9a3.5 3.5 0 0 1 5 5l-9 9a2 2 0 0 1-3-3l7.5-7.5"
              />
            </svg>
            <input
              type="file"
              multiple
              class="brw-svelte-file-input"
              on:change={handleFiles}
              disabled={attachmentsAtCap || $status === 'submitting'}
              aria-label={attachmentsAtCap
                ? `Maximum ${MAX_ATTACHMENTS} attachments reached`
                : 'Attach file'}
            />
          </label>
          <textarea
            class="brw-svelte-textarea"
            rows={2}
            placeholder="Describe the bug or feedback…"
            bind:value={draft}
            on:keydown={handleKeydown}
            aria-label="Feedback message"
            disabled={$status === 'submitting'}
          ></textarea>
          <button
            type="button"
            class="brw-svelte-send"
            aria-label="Send"
            on:click={handleSubmit}
            disabled={!canSend}
          >
            <svg
              viewBox="0 0 24 24"
              width="18"
              height="18"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <path d="M4 20l16-8L4 4l2 8-2 8z" />
              <path d="M6 12h14" />
            </svg>
          </button>
        </div>

        <footer class="brw-svelte-footer">
          <a
            class="brw-svelte-footer-link"
            href="https://brevwick.dev"
            target="_blank"
            rel="noopener noreferrer"
          >
            Brevwick v{BREVWICK_SVELTE_VERSION}
          </a>
        </footer>
      </div>
    {/if}

    <button
      type="button"
      class="brw-svelte-fab {fabPosClass}"
      data-brevwick-skip
      data-testid="brw-svelte-fab"
      aria-label="Open feedback form"
      {disabled}
      on:click={toggleOpen}
    >
      <svg
        viewBox="0 0 24 24"
        width="18"
        height="18"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <path d="M21 12a8 8 0 0 1-11.6 7.1L4 20l1-4.6A8 8 0 1 1 21 12z" />
      </svg>
      <span>{label}</span>
    </button>
  </div>
{/if}

<style>
  /* Public theme tokens, mirrored from the React adapter so the same
     `--brw-*` overrides re-skin both widgets. Defaults are scoped to the
     widget root so a host page's design system is unaffected. */
  .brw-svelte-root {
    --brw-fg: #0b0b0c;
    --brw-fg-muted: #6b7280;
    --brw-bg: #ffffff;
    --brw-panel-bg: var(--brw-bg);
    --brw-bubble-assistant-bg: #f3f4f6;
    --brw-chip-bg: #f3f4f6;
    --brw-composer-bg: #ffffff;
    --brw-border: #e5e7eb;
    --brw-border-focus: #818cf8;
    --brw-divider: #e5e7eb;
    --brw-accent: #4f46e5;
    --brw-accent-fg: #ffffff;
    --brw-shadow:
      0 1px 2px rgba(0, 0, 0, 0.06), 0 8px 24px rgba(0, 0, 0, 0.12);
    color: var(--brw-fg);
    font-family:
      system-ui,
      -apple-system,
      'Segoe UI',
      Roboto,
      sans-serif;
    font-size: 14px;
  }

  .brw-svelte-root[data-brw-theme='dark'],
  :global(.brw-svelte-root[data-brw-theme='system']) {
    /* placeholder; the @media block below handles system dark mode */
  }

  .brw-svelte-root[data-brw-theme='dark'] {
    --brw-fg: #f3f4f6;
    --brw-fg-muted: #9ca3af;
    --brw-bg: #0b0b0c;
    --brw-panel-bg: #111113;
    --brw-bubble-assistant-bg: #1f2024;
    --brw-chip-bg: #1f2024;
    --brw-composer-bg: #111113;
    --brw-border: #2a2b30;
    --brw-divider: #2a2b30;
    --brw-accent: #818cf8;
    --brw-accent-fg: #0b0b0c;
  }

  @media (prefers-color-scheme: dark) {
    .brw-svelte-root[data-brw-theme='system'] {
      --brw-fg: #f3f4f6;
      --brw-fg-muted: #9ca3af;
      --brw-bg: #0b0b0c;
      --brw-panel-bg: #111113;
      --brw-bubble-assistant-bg: #1f2024;
      --brw-chip-bg: #1f2024;
      --brw-composer-bg: #111113;
      --brw-border: #2a2b30;
      --brw-divider: #2a2b30;
      --brw-accent: #818cf8;
      --brw-accent-fg: #0b0b0c;
    }
  }

  .brw-svelte-fab {
    position: fixed;
    bottom: 24px;
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 16px;
    border-radius: 999px;
    border: 1px solid var(--brw-border);
    background: var(--brw-panel-bg);
    color: var(--brw-fg);
    box-shadow: var(--brw-shadow);
    cursor: pointer;
    font: inherit;
    z-index: 2147483646;
  }
  .brw-svelte-fab:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .brw-svelte-fab.brw-fab-br {
    right: 24px;
  }
  .brw-svelte-fab.brw-fab-bl {
    left: 24px;
  }

  .brw-svelte-panel {
    position: fixed;
    bottom: 88px;
    width: min(380px, calc(100vw - 32px));
    max-height: min(640px, calc(100vh - 120px));
    display: flex;
    flex-direction: column;
    background: var(--brw-panel-bg);
    color: var(--brw-fg);
    border: 1px solid var(--brw-border);
    border-radius: 16px;
    box-shadow: var(--brw-shadow);
    overflow: hidden;
    z-index: 2147483647;
  }
  .brw-svelte-panel.brw-panel-br {
    right: 24px;
  }
  .brw-svelte-panel.brw-panel-bl {
    left: 24px;
  }

  .brw-svelte-header {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px 14px;
    border-bottom: 1px solid var(--brw-divider);
  }
  .brw-svelte-avatar {
    width: 24px;
    height: 24px;
    border-radius: 999px;
    background: var(--brw-accent);
    color: var(--brw-accent-fg);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    font-weight: 600;
    font-size: 12px;
  }
  .brw-svelte-title {
    flex: 1;
    font-weight: 600;
  }
  .brw-svelte-icon-btn {
    appearance: none;
    border: none;
    background: transparent;
    color: var(--brw-fg);
    width: 28px;
    height: 28px;
    border-radius: 8px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    font: inherit;
    font-size: 18px;
  }
  .brw-svelte-icon-btn:hover {
    background: var(--brw-bubble-assistant-bg);
  }
  .brw-svelte-icon-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .brw-svelte-thread {
    flex: 1 1 auto;
    overflow-y: auto;
    padding: 12px 14px;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .brw-svelte-bubble {
    padding: 8px 12px;
    border-radius: 12px;
    max-width: 100%;
    line-height: 1.4;
  }
  .brw-svelte-bubble--assistant {
    background: var(--brw-bubble-assistant-bg);
    align-self: flex-start;
  }
  .brw-svelte-bubble--receipt {
    color: var(--brw-fg-muted);
  }

  .brw-svelte-chip {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 6px 10px;
    background: var(--brw-chip-bg);
    border-radius: 8px;
    align-self: flex-start;
    max-width: 100%;
  }
  .brw-svelte-chip-thumb {
    width: 24px;
    height: 24px;
    object-fit: cover;
    border-radius: 4px;
  }
  .brw-svelte-chip-name {
    font-size: 13px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .brw-svelte-chip-size {
    color: var(--brw-fg-muted);
    font-size: 12px;
  }
  .brw-svelte-chip-remove {
    appearance: none;
    border: none;
    background: transparent;
    color: var(--brw-fg-muted);
    cursor: pointer;
    font: inherit;
    font-size: 16px;
    padding: 0 4px;
  }

  .brw-svelte-error {
    color: #b91c1c;
    background: #fef2f2;
    border: 1px solid #fecaca;
    border-radius: 8px;
    padding: 8px 10px;
    font-size: 13px;
  }

  .brw-svelte-composer {
    display: grid;
    grid-template-columns: auto auto 1fr auto;
    gap: 6px;
    align-items: end;
    padding: 10px 12px;
    background: var(--brw-composer-bg);
    border-top: 1px solid var(--brw-divider);
  }
  .brw-svelte-textarea {
    grid-column: 1 / -1;
    width: 100%;
    border: 1px solid var(--brw-border);
    border-radius: 10px;
    padding: 8px 10px;
    background: var(--brw-bg);
    color: var(--brw-fg);
    resize: none;
    font: inherit;
    box-sizing: border-box;
  }
  .brw-svelte-textarea:focus {
    outline: none;
    border-color: var(--brw-border-focus);
  }
  .brw-svelte-send {
    appearance: none;
    border: none;
    background: var(--brw-accent);
    color: var(--brw-accent-fg);
    width: 36px;
    height: 36px;
    border-radius: 999px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    font: inherit;
  }
  .brw-svelte-send:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .brw-svelte-file-input {
    position: absolute;
    width: 1px;
    height: 1px;
    opacity: 0;
    pointer-events: none;
  }

  .brw-svelte-footer {
    padding: 6px 12px 10px;
    text-align: center;
    border-top: 1px solid var(--brw-divider);
  }
  .brw-svelte-footer-link {
    color: var(--brw-fg-muted);
    font-size: 11px;
    text-decoration: none;
  }
</style>

// packages/react/src/feedback-button.tsx
'use client';

import * as Dialog from '@radix-ui/react-dialog';
import {
  useCallback,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
  type KeyboardEvent,
  type ReactElement,
  type ReactNode,
} from 'react';
import type {
  FeedbackAttachment,
  FeedbackInput,
  SubmitResult,
} from 'brevwick-sdk';
import { useFeedback } from './use-feedback';
import { BREVWICK_CSS, BREVWICK_STYLE_ID } from './styles';

/**
 * Props for {@link FeedbackButton}. See SDD § 12 for the React contract.
 */
export interface FeedbackButtonProps {
  /** Corner the FAB pins to. Default `'bottom-right'`. */
  position?: 'bottom-right' | 'bottom-left';
  /** When true, the FAB renders as disabled and cannot open the dialog. */
  disabled?: boolean;
  /** When true, the component renders nothing. Useful for feature-flagging. */
  hidden?: boolean;
  /** Additional class appended to the FAB and dialog root for styling overrides. */
  className?: string;
  /** FAB label. Default `'Feedback'`. */
  label?: ReactNode;
  /** Fired with the SDK's `SubmitResult` after every submit (success or failure). */
  onSubmit?: (result: SubmitResult) => void;
}

const GREETING =
  "Hi! Tell us what's happening. A screenshot helps if you have one.";

const useIsomorphicLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffect : useEffect;

/**
 * Module-level guard so the <style> tag is inserted at most once per session
 * regardless of how many <FeedbackButton>s mount. React does not dedupe
 * `<style>` by id, so render-time injection would produce duplicates for
 * consumers who render multiple buttons.
 */
let hasInjectedStyles = false;

function useBrevwickStyles(): void {
  useIsomorphicLayoutEffect(() => {
    if (hasInjectedStyles) return;
    if (typeof document === 'undefined') return;
    if (document.getElementById(BREVWICK_STYLE_ID)) {
      hasInjectedStyles = true;
      return;
    }
    const el = document.createElement('style');
    el.id = BREVWICK_STYLE_ID;
    el.textContent = BREVWICK_CSS;
    document.head.appendChild(el);
    hasInjectedStyles = true;
  }, []);
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} kB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

interface ScreenshotAttachment {
  readonly blob: Blob;
  readonly url: string;
}

export function FeedbackButton({
  position = 'bottom-right',
  disabled = false,
  hidden = false,
  className,
  label = 'Feedback',
  onSubmit,
}: FeedbackButtonProps): ReactElement | null {
  const { submit, captureScreenshot, status, reset } = useFeedback();
  const [open, setOpen] = useState(false);
  const [draft, setDraft] = useState('');
  const [expected, setExpected] = useState('');
  const [actual, setActual] = useState('');
  const [showExtras, setShowExtras] = useState(false);
  const [screenshot, setScreenshot] = useState<ScreenshotAttachment | null>(
    null,
  );
  const [files, setFiles] = useState<File[]>([]);
  const [confirmClose, setConfirmClose] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [succeeded, setSucceeded] = useState(false);
  const mountedRef = useRef(true);
  const screenshotUrlRef = useRef<string | null>(null);

  useBrevwickStyles();

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      if (screenshotUrlRef.current) {
        URL.revokeObjectURL(screenshotUrlRef.current);
        screenshotUrlRef.current = null;
      }
    };
  }, []);

  useEffect(() => {
    screenshotUrlRef.current = screenshot?.url ?? null;
  }, [screenshot]);

  const hasContent =
    draft.trim().length > 0 ||
    expected.length > 0 ||
    actual.length > 0 ||
    screenshot !== null ||
    files.length > 0;

  const resetAll = useCallback(() => {
    setDraft('');
    setExpected('');
    setActual('');
    setShowExtras(false);
    setScreenshot((prev) => {
      if (prev) URL.revokeObjectURL(prev.url);
      return null;
    });
    setFiles([]);
    setConfirmClose(false);
    setSubmitError(null);
    setSucceeded(false);
    reset();
  }, [reset]);

  const handleFullClose = useCallback(() => {
    setOpen(false);
    resetAll();
  }, [resetAll]);

  const handleMinimize = useCallback(() => {
    setOpen(false);
    setConfirmClose(false);
    setSubmitError(null);
  }, []);

  // Radix routes Esc, overlay clicks, and parent setOpen through onOpenChange.
  // Map a programmatic close-to-false to 'minimize' semantics so Esc preserves
  // the user's draft. The × button handles the dirty-confirm flow directly.
  const handleOpenChange = useCallback(
    (next: boolean) => {
      if (next) {
        setOpen(true);
        return;
      }
      handleMinimize();
    },
    [handleMinimize],
  );

  const handleCloseClick = useCallback(() => {
    if (succeeded) {
      handleFullClose();
      return;
    }
    if (hasContent) {
      setConfirmClose(true);
      return;
    }
    handleFullClose();
  }, [succeeded, hasContent, handleFullClose]);

  const handleCaptureScreenshot = useCallback(async () => {
    setSubmitError(null);
    try {
      const blob = await captureScreenshot();
      if (!mountedRef.current) return;
      setScreenshot((prev) => {
        if (prev) URL.revokeObjectURL(prev.url);
        return { blob, url: URL.createObjectURL(blob) };
      });
    } catch (err) {
      if (!mountedRef.current) return;
      const message =
        err instanceof Error ? err.message : 'Screenshot capture failed';
      setSubmitError(message);
    }
  }, [captureScreenshot]);

  const handleFiles = useCallback((list: FileList | null) => {
    if (!list || list.length === 0) return;
    setFiles((prev) => [...prev, ...Array.from(list)]);
  }, []);

  const removeScreenshot = useCallback(() => {
    setScreenshot((prev) => {
      if (prev) URL.revokeObjectURL(prev.url);
      return null;
    });
  }, []);

  const removeFile = useCallback((index: number) => {
    setFiles((prev) => prev.filter((_, i) => i !== index));
  }, []);

  const doSubmit = useCallback(async () => {
    if (status === 'submitting') return;
    if (!draft.trim()) {
      setSubmitError('Please describe what happened.');
      return;
    }
    setSubmitError(null);

    const attachments: Array<Blob | FeedbackAttachment> = [];
    if (screenshot) {
      const ext = screenshot.blob.type.split('/')[1]?.split('+')[0] || 'webp';
      attachments.push({
        blob: screenshot.blob,
        filename: `screenshot.${ext}`,
      });
    }
    for (const f of files) attachments.push({ blob: f, filename: f.name });

    const trimmed = draft.trim();
    const derivedTitle = trimmed.split('\n', 1)[0]!.slice(0, 120);
    const input: FeedbackInput = {
      title: derivedTitle,
      description: trimmed,
      expected: expected.trim() || undefined,
      actual: actual.trim() || undefined,
      attachments: attachments.length ? attachments : undefined,
    };

    try {
      const result = await submit(input);
      if (!mountedRef.current) return;
      onSubmit?.(result);
      if (result.ok) {
        setSucceeded(true);
      } else {
        setSubmitError(result.error.message);
      }
    } catch (err) {
      if (!mountedRef.current) return;
      const message =
        err instanceof Error && err.message
          ? err.message
          : 'We could not submit your feedback. Please try again.';
      setSubmitError(message);
    }
  }, [actual, draft, expected, files, onSubmit, screenshot, status, submit]);

  if (hidden) return null;

  const fabPosClass = position === 'bottom-left' ? 'brw-fab-bl' : 'brw-fab-br';
  const panelPosClass =
    position === 'bottom-left' ? 'brw-panel-bl' : 'brw-panel-br';
  const rootClassName = ['brw-root', className].filter(Boolean).join(' ');

  return (
    <Dialog.Root open={open} onOpenChange={handleOpenChange}>
      <Dialog.Trigger asChild>
        <button
          type="button"
          data-brevwick-skip=""
          className={`${rootClassName} brw-fab ${fabPosClass}`}
          disabled={disabled}
          aria-label="Open feedback form"
        >
          <ChatIcon />
          {label}
        </button>
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Content
          data-brevwick-skip=""
          className={`${rootClassName} brw-panel ${panelPosClass}`}
          aria-describedby={undefined}
          onInteractOutside={(e) => {
            // Overlay-click semantics: treat the same as Esc (minimize, preserve).
            // Radix already routes through onOpenChange, so no extra state work.
            e.preventDefault();
            handleMinimize();
          }}
        >
          <PanelHeader onMinimize={handleMinimize} onClose={handleCloseClick} />
          {succeeded ? (
            <SuccessState onSendAnother={resetAll} />
          ) : (
            <Thread
              greeting={GREETING}
              draft={draft}
              screenshot={screenshot}
              files={files}
              showExtras={showExtras}
              expected={expected}
              actual={actual}
              confirmClose={confirmClose}
              submitError={submitError}
              status={status}
              onToggleExtras={() => setShowExtras((v) => !v)}
              onExpectedChange={setExpected}
              onActualChange={setActual}
              onRemoveScreenshot={removeScreenshot}
              onRemoveFile={removeFile}
              onConfirmDiscard={handleFullClose}
              onCancelClose={() => setConfirmClose(false)}
            />
          )}
          {!succeeded && (
            <Composer
              draft={draft}
              submitting={status === 'submitting'}
              onDraftChange={setDraft}
              onSubmit={doSubmit}
              onAttachScreenshot={handleCaptureScreenshot}
              onAttachFiles={handleFiles}
            />
          )}
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}

interface PanelHeaderProps {
  onMinimize: () => void;
  onClose: () => void;
}

function PanelHeader({ onMinimize, onClose }: PanelHeaderProps): ReactElement {
  return (
    <div className="brw-panel-header">
      <span className="brw-panel-avatar" aria-hidden="true">
        B
      </span>
      <Dialog.Title className="brw-panel-title">Send feedback</Dialog.Title>
      <button
        type="button"
        className="brw-icon-btn"
        aria-label="Minimize"
        onClick={onMinimize}
      >
        <MinimizeIcon />
      </button>
      <button
        type="button"
        className="brw-icon-btn"
        aria-label="Close"
        onClick={onClose}
      >
        <CloseIcon />
      </button>
    </div>
  );
}

interface ThreadProps {
  greeting: string;
  draft: string;
  screenshot: ScreenshotAttachment | null;
  files: readonly File[];
  showExtras: boolean;
  expected: string;
  actual: string;
  confirmClose: boolean;
  submitError: string | null;
  status: 'idle' | 'submitting' | 'success' | 'error';
  onToggleExtras: () => void;
  onExpectedChange: (v: string) => void;
  onActualChange: (v: string) => void;
  onRemoveScreenshot: () => void;
  onRemoveFile: (index: number) => void;
  onConfirmDiscard: () => void;
  onCancelClose: () => void;
}

function Thread({
  greeting,
  draft,
  screenshot,
  files,
  showExtras,
  expected,
  actual,
  confirmClose,
  submitError,
  status,
  onToggleExtras,
  onExpectedChange,
  onActualChange,
  onRemoveScreenshot,
  onRemoveFile,
  onConfirmDiscard,
  onCancelClose,
}: ThreadProps): ReactElement {
  const trimmed = draft.trim();
  return (
    <div
      className="brw-thread"
      role="log"
      aria-live="polite"
      aria-label="Conversation"
    >
      <AssistantBubble>{greeting}</AssistantBubble>
      {trimmed.length > 0 && <UserBubble>{draft}</UserBubble>}
      {screenshot && (
        <AttachmentChip
          name="screenshot"
          size={screenshot.blob.size}
          previewUrl={screenshot.url}
          onRemove={onRemoveScreenshot}
        />
      )}
      {files.map((f, i) => (
        <AttachmentChip
          key={`${f.name}-${i}`}
          name={f.name}
          size={f.size}
          onRemove={() => onRemoveFile(i)}
        />
      ))}
      <DisclosureExpectedActual
        open={showExtras}
        expected={expected}
        actual={actual}
        onToggle={onToggleExtras}
        onExpectedChange={onExpectedChange}
        onActualChange={onActualChange}
      />
      {submitError && (
        <div className="brw-error" role="alert">
          {submitError}
        </div>
      )}
      {status === 'submitting' && (
        <AssistantBubble>
          <span className="brw-spinner" aria-hidden="true" /> Sending…
        </AssistantBubble>
      )}
      {confirmClose && (
        <div
          className="brw-confirm"
          role="alertdialog"
          aria-label="Discard draft?"
        >
          <span className="brw-confirm-msg">Discard your feedback?</span>
          <button type="button" className="brw-btn" onClick={onCancelClose}>
            Keep
          </button>
          <button
            type="button"
            className="brw-btn brw-btn-primary"
            onClick={onConfirmDiscard}
          >
            Discard
          </button>
        </div>
      )}
    </div>
  );
}

function AssistantBubble({ children }: { children: ReactNode }): ReactElement {
  return <div className="brw-bubble brw-bubble--assistant">{children}</div>;
}

function UserBubble({ children }: { children: ReactNode }): ReactElement {
  return <div className="brw-bubble brw-bubble--user">{children}</div>;
}

interface AttachmentChipProps {
  name: string;
  size: number;
  previewUrl?: string;
  onRemove: () => void;
}

function AttachmentChip({
  name,
  size,
  previewUrl,
  onRemove,
}: AttachmentChipProps): ReactElement {
  return (
    <div className="brw-chip">
      {previewUrl && <img src={previewUrl} alt="" />}
      <span className="brw-chip-name">{name}</span>
      <span className="brw-chip-size">{formatSize(size)}</span>
      <button
        type="button"
        className="brw-chip-remove"
        aria-label={`Remove ${name}`}
        onClick={onRemove}
      >
        ×
      </button>
    </div>
  );
}

interface DisclosureProps {
  open: boolean;
  expected: string;
  actual: string;
  onToggle: () => void;
  onExpectedChange: (v: string) => void;
  onActualChange: (v: string) => void;
}

function DisclosureExpectedActual({
  open,
  expected,
  actual,
  onToggle,
  onExpectedChange,
  onActualChange,
}: DisclosureProps): ReactElement {
  const panelId = 'brw-extras-panel';
  return (
    <>
      <button
        type="button"
        className="brw-disclosure"
        aria-expanded={open}
        aria-controls={panelId}
        onClick={onToggle}
      >
        {open ? 'Hide expected vs actual' : 'Add expected vs actual'}
      </button>
      {open && (
        <div id={panelId} className="brw-disclosure-panel">
          <label>
            <span className="brw-disclosure-label">Expected</span>
            <textarea
              className="brw-disclosure-input"
              rows={2}
              value={expected}
              onChange={(e) => onExpectedChange(e.target.value)}
            />
          </label>
          <label>
            <span className="brw-disclosure-label">Actual</span>
            <textarea
              className="brw-disclosure-input"
              rows={2}
              value={actual}
              onChange={(e) => onActualChange(e.target.value)}
            />
          </label>
        </div>
      )}
    </>
  );
}

interface ComposerProps {
  draft: string;
  submitting: boolean;
  onDraftChange: (v: string) => void;
  onSubmit: () => void;
  onAttachScreenshot: () => void;
  onAttachFiles: (list: FileList | null) => void;
}

function Composer({
  draft,
  submitting,
  onDraftChange,
  onSubmit,
  onAttachScreenshot,
  onAttachFiles,
}: ComposerProps): ReactElement {
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  // Autogrow between ~1 and ~5 rows. Max-height from CSS bounds it; measuring
  // scrollHeight each keystroke is cheap next to React's own render cost.
  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = `${Math.min(el.scrollHeight, 120)}px`;
  }, [draft]);

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>): void => {
    if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault();
      onSubmit();
    }
  };

  return (
    <div className="brw-composer">
      <button
        type="button"
        className="brw-icon-btn"
        aria-label="Attach screenshot"
        onClick={onAttachScreenshot}
        disabled={submitting}
      >
        <CameraIcon />
      </button>
      <label className="brw-icon-btn" aria-label="Attach file">
        <PaperclipIcon />
        <input
          type="file"
          multiple
          className="brw-file-input"
          onChange={(e) => {
            onAttachFiles(e.target.files);
            e.target.value = '';
          }}
          disabled={submitting}
        />
      </label>
      <textarea
        ref={textareaRef}
        className="brw-composer-input"
        rows={1}
        placeholder="Describe the bug or feedback…"
        value={draft}
        onChange={(e) => onDraftChange(e.target.value)}
        onKeyDown={handleKeyDown}
        aria-label="Feedback message"
      />
      <button
        type="button"
        className="brw-send-btn"
        aria-label="Send"
        disabled={submitting || draft.trim().length === 0}
        onClick={onSubmit}
      >
        <SendIcon />
      </button>
    </div>
  );
}

interface SuccessStateProps {
  onSendAnother: () => void;
}

function SuccessState({ onSendAnother }: SuccessStateProps): ReactElement {
  return (
    <div
      className="brw-thread"
      role="log"
      aria-live="polite"
      aria-label="Confirmation"
    >
      <div className="brw-success-wrap">
        <div className="brw-bubble brw-bubble--success" role="status">
          Thanks — your report is on its way.
        </div>
        <button
          type="button"
          className="brw-btn brw-btn-primary"
          onClick={onSendAnother}
        >
          Send another
        </button>
      </div>
    </div>
  );
}

function ChatIcon(): ReactElement {
  return (
    <svg
      className="brw-fab-icon"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 12a8 8 0 0 1-11.6 7.1L4 20l1-4.6A8 8 0 1 1 21 12z" />
    </svg>
  );
}

function MinimizeIcon(): ReactElement {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M5 14h14" />
    </svg>
  );
}

function CloseIcon(): ReactElement {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M6 6l12 12M18 6L6 18" />
    </svg>
  );
}

function CameraIcon(): ReactElement {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M3 7h4l2-3h6l2 3h4v12H3z" />
      <circle cx="12" cy="13" r="4" />
    </svg>
  );
}

function PaperclipIcon(): ReactElement {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M21 10.5l-8.5 8.5a5 5 0 0 1-7-7l9-9a3.5 3.5 0 0 1 5 5l-9 9a2 2 0 0 1-3-3l7.5-7.5" />
    </svg>
  );
}

function SendIcon(): ReactElement {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M4 20l16-8L4 4l2 8-2 8z" />
      <path d="M6 12h14" />
    </svg>
  );
}
